### ISSUE TITLE
Update for v4 USI TSC endpoint

### ISSUE THREAD

**Issue by dkfthiggins** [bartland-usi/sample-java#10]
Hi Bruce,

Just wondering if there is an update coming for the java sample to work with the new USI v4 endpoint (https://3pt.portal.usi.gov.au/Service/UsiService.svc) including the changes to the WSDL for the preconfigured STS that you did for v3?

Thanks,
Dave

**Comment by bartland** [comment]
Done. Tested on Linux. Will test on Windows/Mac shortly (no changes expected).

Regards

**Comment by dkfthiggins** [comment]
Cheers for that Bruce, will give it a test as soon as I can.
