### ISSUE TITLE
Seperation of concerns security and calling USI services

### ISSUE THREAD

**Issue by SwTiwari** [bartland-usi/sample-java#17]
This is more of a query rather than an issue.

Thanks team ,we are able to run the implementation https://github.com/bartland-usi/sample-java but looking to segregate the two concerns of fetching the  token  and calling the webservice a in different components.  

Are you aware of any  sample application or documentation to get just the token . We need this as a separate component to enable us to reuse it in future to call some other gov service.

Also are you aware if there is any strategy for new /different  GOV service to use the same authentication/authorization process .
 
I would appreciate any insight into it. 

Thanks
Swati

**Comment by bartland** [comment]
Separation of concerns: There is a Java kit available which just fetches the token. You can register with the SBR Developer program to get it. However, there is no client kit that then uses the token to interact with USI as a separate step. Would like to see that myself. There is a separate client kit for SBR.

The only RelyingParty services I am aware of that are publicly available are SBR and USI. However there may be others.

Cheers
