### ISSUE TITLE
Event Description: [The security token could not be authenticated or authorized for the delegation.]. User Advice: [Advise business user the service is unable to authenticate the request for this supplied delegation.].

### ISSUE THREAD

**Issue by sgbell** [bartland-usi/sample-java#19]
Hi Bruce,
   Love your work. I've attempted to merge your code into our own codebase. I got the stsver=13 working for local requests, so now I'm trying to make my life easier deployment wise, and go for the M2M connection (if it saves me spinning up one for a number of clients, and Just direct them to a single app server).
I'm getting the above error now. I haven't checked with USI's IT Support yet, because I just wanted to sanity check.
I have gone back and run your sample code as instructed, and I'm getting the same result. I Suppose I'm just asking.. is it broken for you too?!. If it is great, I'll contact USI's IT Support.
I'm sure I had it running 2 weeks ago, and signed off on the code, and when I've gone to deploy to my test server for integration testing it appears the M2M credentials are broken. But seen as your test code doesn't seem to be working for me either, I'm thinking the 3rd party auth is broken on the gov side.

`  [java] javax.xml.ws.soap.SOAPFaultException: Delegation error. Event Code: [E9008]. Event Severity: [Normal]. Event Description: [The security token could not be authenticated or authorized for the delegation.]. User Advice: [Advise business user the service is unable to authenticate the request for this supplied delegation.]. Agency Reference: [uuid:67768549-8f5c-4cbe-96f4-bddd503ddf45]. Transaction Id: [d067a3d9-a348-4bee-b703-13e0cde525ca].
     [java]     at com.sun.xml.ws.security.trust.impl.wssx.WSTrustElementFactoryImpl.checkElement(WSTrustElementFactoryImpl.java:883)
     [java]     at com.sun.xml.ws.security.trust.impl.wssx.WSTrustElementFactoryImpl.createRSTRCollectionFrom(WSTrustElementFactoryImpl.java:465)
     [java]     at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.parseRSTR(TrustPluginImpl.java:724)
     [java]     at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.invokeRST(TrustPluginImpl.java:603)
     [java]     at com.sun.xml.ws.security.trust.impl.TrustPluginImpl.process(TrustPluginImpl.java:145)
     [java]     at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.getIssuedTokenContext(STSIssuedTokenProviderImpl.java:114)
     [java]     at com.sun.xml.ws.security.trust.impl.client.STSIssuedTokenProviderImpl.issue(STSIssuedTokenProviderImpl.java:44)
     [java]     at com.sun.xml.ws.api.security.trust.client.IssuedTokenManager.getIssuedToken(IssuedTokenManager.java:53)
     [java]     at com.sun.xml.wss.jaxws.impl.SecurityClientTube.invokeTrustPlugin(SecurityClientTube.java:660)
     [java]     at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processClientRequestPacket(SecurityClientTube.java:253)
     [java]     at com.sun.xml.wss.jaxws.impl.SecurityClientTube.processRequest(SecurityClientTube.java:219)
     [java]     at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:1106)
     [java]     at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:1020)
     [java]     at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:989)
     [java]     at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:847)
     [java]     at com.sun.xml.ws.client.Stub.process(Stub.java:433)
     [java]     at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:161)
     [java]     at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
     [java]     at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62)
     [java]     at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131)
     [java]     at com.sun.proxy.$Proxy47.createUSI(Unknown Source)
     [java]     at usi.gov.au.USITest.main(Unknown Source)`

**Comment by bartland** [comment]
Please try the latest update in 3PT which supports v4 and v5 USI service. PROD support for v5 pending an ATO update to their service.

v3 service is deprecated.
