### ISSUE TITLE
USI Java sample doesn't seem to work now

### ISSUE THREAD

**Issue by dkfthiggins** [bartland-usi/sample-java#20]
Hi Bruce,

Not sure if the service endpoint has changed (it seems the test one is using mixed case now too) but the sample code isn't working against 3PT v1.4 anymore.  We have clients reporting the issue with our java client, and on testing the sample (after a fresh install from the fork https://github.com/bartland/sample-java) it is giving the same issue.  Initially it was an outdated keystore, but we were given a new keystore and the issue is now the AppliesTo:

"The relying party specified in the AppliesTo element is not recognized."

The AppliesTo generated is:
   <wsp:AppliesTo>
      <wsa:EndpointReference>
         <wsa:Address>https://3pt.portal.usi.gov.au/service/usiservice.svc</wsa:Address>
      </wsa:EndpointReference>
   </wsp:AppliesTo>

Can you take a look and see if the sample is working (forked version you gave us last time too)

Thanks,
David
Tribal Group

**Comment by bartland** [comment]
Please try the latest update in 3PT which supports v4 and v5 USI service. PROD support for v5 pending an ATO update to their service.
