### ISSUE TITLE
Issues with Authentication

### ISSUE THREAD

**Issue by alexatqtac** [bartland-usi/sample-java#21]
When attempting to use this sample and also regenerating the wsdl classes using apache cxf as well I am seeing the following error:

`WST0017:Could not obtain STS metadata. MEX call to STS https://softwareauthorisations.acc.ato.gov.au/R3.0/S007v1.3/service.svc/mex failed.`

The credentials we are using appear to be the latest test credentials provided by USI as well and we are getting the same error whether we are using the test or prod environment as well (just to confirm).

Any help you could provide would be greatly appreciated and I'm happy to provide more information as well (I just figured this is a good place to start).

Thanks, Alex

**Comment by bartland** [comment]
Please try the latest update in 3PT. It should work "out of the box".
