### ISSUE TITLE
Unable to update to USI version 5

### ISSUE THREAD

**Issue by scottdoc** [bartland-usi/sample-java#27]
Hello,

So I have been able to update the code for USI version 5. It is mostly just namespace changes in the WSDL and a few added validation. There are also new testing credentials.

The problem is I cannot get the test to run because of a difference between the AppliesTo URL and the endpoint URL. I can't seem to make the code use 2 different URLs and was wondering if there was some way to do that in this Java framework.

According to the v5 documents, the service endpoint, defined at the bottom of the new WSDL, is now supposed to be: 

`<wsa10:Address>https://3pt.portal.usi.gov.au/Service/v5/UsiService.svc</wsa10:Address>`

However, if I use that, then the auth call to the ATO fails with `The relying party specified in the AppliesTo element is not recognized`

If I instead use the correct AppliesTo element here (all lower case), `<wsa10:Address>https://3pt.portal.usi.gov.au/service/usiservice.svc</wsa10:Address>`

Then the ATO call succeeds but then the subsequent call to the USI is now at that old address and returns the rather wordy error:

`The message with Action 'http://usi.gov.au/2022/ws/GetCountries' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).` 

Does anyone know how to get the service to use a different appliesTo vs endpoint URL?

**Comment by Nicooooo** [comment]
Hi @scottdoc, have you fixed this issue? I'm also having troubles on this one.

**Comment by scottdoc** [comment]
Hi @Nicooooo - No I haven't, actually. I have also left a question on the CXF mailing list, but so far no one has replied.

**Comment by prachi-a-joglekar** [comment]
@scottdoc : Even i am facing same issue. The expectation is to separate the two requests, authenticate first and then make a separate call. Not sure how to go about it

**Comment by scottdoc** [comment]
@prachi-a-joglekar I'd be very interested if you can find out a way to do it. I've tried interceptors and handlers and nothing I've tried has allowed me to break or adjust the call between those 2 points.

**Comment by scottdoc** [comment]
If it helps, I have created a fork to test USI v5
https://github.com/scottdoc/sample-java-v5

If anyone finds a solution please contribute - we can perhaps merge it back into this main one if we can get it working

**Comment by Nicooooo** [comment]
Hello there, i have communicated this with the USI team and they've raised it on the ATO.
Currently, I have tested it and we can now use https://3pt.portal.usi.gov.au/service/v5/usiservice.svc

**Comment by scottdoc** [comment]
That's great news, @Nicooooo - and updating the ATO side so that it recognises the correct endpoint really is the best and most correct solution. However, I'm still getting the `The relying party specified in the AppliesTo element is not recognized` error. 

Did they say when the change will roll out? And will it work for both STS 1.2 and 1.3 and for both the testing (3pt) and production endpoints?

**Comment by scottdoc** [comment]
Have just heard back from the USI - and the lowercase version of the URL does now work with the ATO STS call: https://3pt.portal.usi.gov.au/service/v5/usiservice.svc

I will close this issue

**Comment by scottdoc** [comment]
I may have closed this too soon. In case anyone is trying, the testing endpoint works, but the production one does not.

**Comment by bartland** [comment]
Updated to support v5 in 3PT and PROD. See README.

PROD is currently not working as we are waiting on ATO to update their service to whitelist the new USI v5 service.
