### ISSUE TITLE
keystore ?

### ISSUE THREAD

**Issue by pwillia6** [bartland-usi/sample-java#4]
Hi Barlant - thanks for this.

I was having a hard time getting this all to work.

A suggestion.  Put this (perhaps commented out) somewhere to turn on SOAP tracing:

`		System.setProperty("com.sun.xml.ws.transport.http.client.HttpTransportPipe.dump", "true");
		System.setProperty("com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump", "true");
		System.setProperty("com.sun.xml.ws.transport.http.HttpAdapter.dump", "true");
		System.setProperty("com.sun.xml.internal.ws.transport.http.HttpAdapter.dump", "true");
		System.setProperty("com.sun.xml.ws.transport.http.HttpAdapter.dumpTreshold", "999999");`

Also the keystore-usi-offline.xml is the only one that seems to work.    Where did you get this from ?

I am not a Java developer so I had a hard time figuring out what was wrong.  

Thanks Again,

Paul.

**Comment by bartland** [comment]
Hi Paul
Sorry for the delayed response. Been caught up in other things. 

Thanks for the feedback. I'll take a look.

The keystore-usi.xml is the file to use as it is issued from the official test CA (Certificate Authority). There have been some issues from time to time that cause that CA to, effectively become unavailable, resulting in errors. Should all be resolved now.

The keystore-usi-offline.xml file is generated from a different CA that doesn't suffer those issues, so can work as a fallback but shouldn't be used normally as the credential structure does not fully reflect that of production credentials.

cheers
