### ISSUE TITLE
external source for assets?

### ISSUE THREAD

**Issue by bopolissimus** [bartland-usi/sample-java#6]
Hello,

Thank you very much for this project.  It's been a huge help with a USI verify project I'm assisting with.

For the 7z files in the assets release (referred to in lib/readme.txt).  Where did you get those from?  Or where could I look for the projects that build those?

We'd use those (source of libs) for security audits and similar.  e.g., we could set up monitoring (or join mailing lists) to be notified of security updates so that updates could be deployed as soon as available.

Many thanks,
Gerald Quimpo

**Comment by bartland** [comment]
Hi Gerald (@bopolissimus)

The source for the metro jars are mentioned in the README.

I'll update the README to mention the source of the "AUSkey" jars. These are from the Java SDK of https://www.sbr.gov.au/digital-service-providers. They change very rarely.
